fix: remove sudo in scripts

diff --git a/Server/Makefile b/Server/Makefile
--- a/Server/Makefile
+++ b/Server/Makefile
@@ -10,10 +10,10 @@ test_flags ?= -vvs
 # Target environment (dev, staging, prod, ci)        
 environment ?= dev
 # Which environment variables to set
-file_env = $(if $(filter ci,$(environment)),.env_dev,.env_$(environment))
+ENV_FILE = $(if $(filter ci,$(environment)),.env_dev,.env_$(environment))
 # Defines the name prefix used by docker-compose for containers
 # depending on the current environment (e.g., dev, staging, prod, ci)
-prefix = $(if $(filter ci,$(environment)),dev_fhe_ios_demo,$(environment)_fhe_ios_demo)
+PREFIX = $(if $(filter ci,$(environment)),dev_fhe_ios_demo,$(environment)_fhe_ios_demo)
 # Docker build cache option. Use '' to enable cache or '--no-cache' to disable it        
 cache ?=
 # Force Rust rebuild. Use '' to enable cache or '--rebuild_rust' to disable it      
@@ -31,10 +31,13 @@ machine ?= c5.4xlarge
 # Tests
 TESTS = ad_targeting weight_stats sleep_quality endpoints
 
-.PHONY: docker_build docker_run docker_build_run tests_build tests_run clean_files benchmark stress_test
+.PHONY: check_certificates certificates
+.PHONY: docker_build docker_run docker_build_run
+.PHONY: tests_build tests_run
+.PHONY: clean_files benchmark
 
-docker_build:
-	sudo bash ./scripts/docker_build.sh $(environment) $(cache) $(rebuild_rust)
+docker_build: check_certificates
+	bash ./scripts/docker_build.sh $(environment) $(cache) $(rebuild_rust)
 
 docker_run:
 	@if [ $$(docker images | grep $$FINAL_IMAGE_NAME | wc -l) -eq 0 ]; then \
@@ -42,15 +45,15 @@ docker_run:
 		echo "Please run: 'make docker_build' first!"; \
 		exit 1; \
 	fi
-	sudo bash ./scripts/docker_run.sh $(environment)
+	bash ./scripts/docker_run.sh $(environment)
 
-docker_build_run:
-	sudo bash ./scripts/docker_build.sh $(environment) $(cache) $(rebuild_rust)
-	sudo bash ./scripts/docker_run.sh $(environment)
+docker_build_run: check_certificates
+	bash ./scripts/docker_build.sh $(environment) $(cache) $(rebuild_rust)
+	bash ./scripts/docker_run.sh $(environment)
 
 tests_build:
-	@echo "🔧 Building test environment for '$(environment)' using '$(file_env)' variables..."
-	@bash -c 'set -a && source $(file_env) && VENV_DIR=$(VENV_DIR) bash ./scripts/tests_build.sh'
+	@echo "🔧 Building test environment for '$(environment)' using '$(ENV_FILE)' variables..."
+	@bash -c 'set -a && source $(ENV_FILE) && VENV_DIR=$(VENV_DIR) && set +a && bash ./scripts/tests_build.sh'
 	@echo "🔨 Building Rust components in Docker..."
 	@docker run --platform linux/amd64 \
 		-v $(PWD):/app \
@@ -70,7 +73,7 @@ tests_run:
 
 	@for test in $(TESTS); do \
 		echo "Running test: $$test"; \
-		bash -c "source $(VENV_DIR)/bin/activate && set -a && source $(file_env) && pytest tests/test_$$test.py $(test_flags)"; \
+		bash -c "source $(VENV_DIR)/bin/activate && set -a && source $(ENV_FILE) && set +a && pytest tests/test_$$test.py $(test_flags)"; \
 	done
 
 clean_files:
@@ -93,12 +96,12 @@ benchmark:
 	@for task in $(TASKS); do \
 		echo "Running $$task..."; \
 		start=$$(date +%s.%N); \
-		bash -c "source $(VENV_DIR)/bin/activate && set -a && source $(file_env) && pytest tests/test_$$task.py"; \
+		bash -c "source $(VENV_DIR)/bin/activate && set -a && source $(ENV_FILE) && set +a && pytest tests/test_$$task.py -vvs"; \
 		end=$$(date +%s.%N); \
 		end_to_end=$$(echo "$$end - $$start" | bc); \
 		echo "🔍 Docker logs for task=$$task | e2e_time=$$end_to_end (s):"; \
-		docker logs $(prefix)_service_celery_usecases_2 2>&1 | grep "🥕 ✅" | grep $$task | tail -n 1; \
-		server_time=$$(docker logs $(prefix)_service_celery_usecases_2 2>&1 \
+		docker logs $(PREFIX)_service_celery_usecases_2 2>&1 | grep "🥕 ✅" | grep $$task | tail -n 1; \
+		server_time=$$(docker logs $(PREFIX)_service_celery_usecases_2 2>&1 \
 			| grep "🥕 ✅" \
 			| grep "$$task" \
 			| tail -n 1 \
@@ -122,3 +125,31 @@ stress_test:
 	@bash -c 'set -a && source .env_$(environment) && source $(VENV_DIR)/bin/activate && python tests/generate_stress_data.py'
 	@echo "🚀 Running stress test against $(environment) server..."
 	@bash -c 'set -a && source .env_$(environment) && source $(VENV_DIR)/bin/activate && python tests/stress_runner.py'
+
+certificates:
+	@if [ "$(environment)" = "dev" ]; then \
+		echo "⚠️  This target should not be run in the 'dev' environment."; \
+		echo "Development uses the HTTP protocol without secure connection."; \
+		exit 1; \
+	fi
+	@echo "Building certificates for '$(environment)' using '$(ENV_FILE)' variables using 'sudo' privileges..."
+	@if [ "$$(id -u)" -ne 0 ]; then \
+		echo "This step requires sudo. Please run: 'sudo make certificates'"; \
+		exit 1; \
+	fi
+	@bash -c ' \
+		set -a && source $(ENV_FILE) && source .common_env && set +a && \
+		bash ./scripts/generate_certificates.sh && \
+		touch /tmp/certificates.done; \
+	'
+
+check_certificates:
+	@bash -c ' \
+		set -a && source $(ENV_FILE) && source .common_env && set +a; \
+		if [ ! -f "$$HOST_CERTS_PATH/$$CERT_FILE_NAME" ] || [ ! -f "$$HOST_CERTS_PATH/$$PRIVKEY_FILE_NAME" ]; then \
+			echo "❌ Certificate files are missing in $$HOST_CERTS_PATH."; \
+			echo "Please run: sudo make certificates"; \
+			exit 1; \
+		else \
+			echo "✅ Certificate files are present in $$HOST_CERTS_PATH."; \
+		fi'
